config/routes.rb
Rails.application.routes.draw do
  root  'static_pages#index'

  match 'about',    to: 'static_pages#about',   via: 'get'
  match 'contact',  to: 'static_pages#contact', via: 'get'

  resources :posts do 
    resources :comments
  end 

  resources :tags
  resources :users

  resources :user_sessions, only: [:new, :create, :destroy ]

  get 'login'     => 'user_sessions#new'
  get 'logout'    => 'user_sessions#destroy'

end

app/models/post.rb
class Post < ActiveRecord::Base
	#validates_presence_of :title
	#validates_presence_od :body 
	validates :title, :body, presence: true
	has_many :comments, dependent: :destroy
	has_many :taggings
	has_many :tags, through: :taggings

	#for paperclip
	has_attached_file :image
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]



	def tag_list
		tags.join(", ")
	end

	def tag_list=(tags_string)
		tag_names = tags_string.split(", ").collect{ |s| s.strip.downcase}.uniq
		new_or_found_tags = tag_names.collect{|name| Tag.find_or_create_by(name: name) }
		self.tags = new_or_found_tags
	end 

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #filter
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  #Allow users to be able to see and index of all the posts or see a particular post
  before_action :authenticate, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
                                  #post_url(@post)
        format.html { redirect_to @post, notice: "'#{@post.title}' was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "'#{@post.title}' was successfully updated."}
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "'#{@post.title}' was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :tag_list, :image)
    end

        #Authenticate function filter before_action: :authenticate
    def authenticate
      authenticate_or_request_with_http_basic do |name, password|
        name == "admin" && password == "secret"
      end 
    end 
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post, html: { multipart: true}) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "Post title"%><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body, "Post body"%><br>
    <%= f.text_area :body %>
  </div>
  <!---tags interface -->
  <div class="field">
    <%= f.label :tag_list %><br>
    <%= f.text_field :tag_list %>
  </div>

  <!---paperclip image uploading -->
  <div class="field">
    <% if @post.image.exists? %>
      <%= image_tag @post.image.url %><br>
    <% end %>
    <%= f.label :image, "Upload an image" %><br>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "Create post", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
	<h1>Editing Post</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @post %> |
	<%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Listing Posts</h1>

  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= link_to post.title, post_path(post)%></td>
          <td><%= post.body %></td>
          <td><%= link_to 'Show', post %></td>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Delete this post', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Post', new_post_path, class: "btn btn-primary"%>
</div>

app/views/posts/new.html.erb
<div class="container">
	<h1>New Post</h1>

	<%= render 'form' %>

	<%= link_to 'Back', posts_path %>	
</div>

app/views/posts/show.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Title:</strong>
	  <%= @post.title %>
	</p>

	<p>
		<% if @post.image.exists? %>
      		<%= image_tag @post.image.url %><br>
    	<% end %>
	</p>
	
	<p>
	  <strong>Tags:</strong>
	  <% @post.tags.each do |tag| %>
		  <%= link_to tag.name, tag_path(tag) %>
	  <% end %>
	</p>

	<p>
	  <strong>Body:</strong>
	  <%= @post.body %>
	</p>

	<!--Display comments for a particular post, comment count -->
	<h4 style="text-align: left;">Comments (<%= @post.comments.size %>)</h4>
	<div id="comments">
		<%= render :partial => @post.comments.reverse %>
	</div>

	<!-- add more comments, create a new form -->
	<%= form_for([@post, Comment.new ], remote: true) do |f| %>
		<p>
			<%= f.label :body, "New Comment" %><br />
			<%= f.text_area :body %><br />
		</p>
		<p><%= f.submit "Add Comment", class: "btn btn-primary"%></p>
	<% end %>


	<%= link_to 'Edit', edit_post_path(@post) %> |
	<%= link_to 'Back', posts_path %>
</div>