config/routes.rb
Rails.application.routes.draw do
  root  'static_pages#index'

  match 'about',    to: 'static_pages#about',   via: 'get'
  match 'contact',  to: 'static_pages#contact', via: 'get'

  resources :posts do 
    resources :comments
  end 

  resources :tags
  resources :users

  resources :user_sessions, only: [:new, :create, :destroy ]

  get 'login'     => 'user_sessions#new'
  get 'logout'    => 'user_sessions#destroy'

end

app/views/layouts/_footer.html.erb
<footer id="footer">
	<p>Hello World!</p>
	
</footer>

app/views/layouts/_header.html.erb
<header class="container-fluid">
	<h1>Welcome to t.Sprinkless Blog</h1>
	<%= image_tag("emejia.png", :alt => "Profile picture", class: "myimg")%>
	<h2>Created by Elvyn Mejia</h2>	
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
     <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Abril+Fatface' rel='stylesheet' type='text/css'>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="logo">
              <div class="ts-opacity">
                <h1>t.Sprinkless</h1>
              </div>
          </div>
        </div>
      </div>
    </div>

  	<div class="container-fluid" id="navbar">
  		<ul>
  			<li><%= link_to "HOME", root_path %></li>
  			<li><%= link_to "ABOUT", about_path %></li>
  			<li><%= link_to "CONTACT", contact_path %></li>
        <li><%= link_to "POSTS", posts_path %></li>
          <% if logged_in? %>
            <li><%= "Logged in as #{current_user.username}" %></li>
            <li><%= link_to "LOGOUT", logout_path %></li>
            <% else %>
            <li><%= link_to "LOGIN", login_path %></li>
            <li><%= link_to 'SIGNUP', new_user_path %></li>
          <% end %>
  		</ul>
  	</div>

   
      <%= yield %>

  </body>
</html>